var res = {
  apple_png : "res/apple.png",
  basket0_png : "res/basket1.png",
  basket1_png : "res/basket2.png",
  basket2_png : "res/basket3.png",
  basket3_png : "res/basket4.png",
  cat0_png : "res/cat0.png",
  cat1_png : "res/cat1.png",
  cat2_png : "res/cat2.png",
  cat3_png : "res/cat3.png",
  bug_png : "res/bug.png",
  game_bg_png : "res/game_bg.png",
  title_bg_png : "res/title_bg.png",
  ranking_bg_png : "res/ranking_bg.png",
  game_cloud_png : "res/game_cloud.png",
  game_counter_png : "res/game_counter.png",
  gameover_png : "res/gameover.png",
  go_png : "res/go.png",
  help0_png : "res/help_1.png",
  help1_png : "res/help_2.png",
  howtoplay0_png : "res/howtoplay1_J.png",
  howtoplay1_png : "res/howtoplay2_J.png",
  howtoplay2_png : "res/howtoplay3_J.png",
  number0_png : "res/number1.png",
  number1_png : "res/number2.png",
  number2_png : "res/number3.png",
  ranking_android_png : "res/ranking_android.png",
  ranking_apple_png : "res/ranking_apple.png",
  ranking_back0_png : "res/ranking_back1.png",
  ranking_back1_png : "res/ranking_back2.png",
  timerleft_png : "res/timeleft.png",
  title_png : "res/title_J.png",
  title_ranking0_png : "res/title_ranking_1_J.png",
  title_ranking1_png : "res/title_ranking_2_J.png",
  title_start0_png : "res/title_start_1_J.png",
  title_start1_png : "res/title_start_2_J.png",
  touchend_png : "res/touchend.png",
  touchorigin_png : "res/touchorigin.png",
  bgm : "res/bgm.mp3",
  se_button : "res/button.mp3",
  se_countdown : "res/countdoun.mp3",
  se_whistle : "res/whistle.mp3"
};

var g_resources = [];
for (var i in res) {
  g_resources.push(res[i]);
}
